apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: market
spec:
  ports:
    - port: 5434
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-notification
  type: ClusterIP
