apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  namespace: market
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8802
  type: ClusterIP