apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: market
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: 2admi/otus-market-notification:1.0.0
          ports:
            - containerPort: 8802
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: DB_HOST
              value: "postgres-notification"
            - name: DB_PORT
              value: "5434"
            - name: DB_NAME
              value: "notification_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
